server {
    listen 80;

    location /health {
        return 200 '{"status":"UP","server":"server2"}';
        add_header Content-Type application/json;
    }

    location / {
        return 200 '{"server":"server2","message":"Hello from Backend 2"}';
        add_header Content-Type application/json;
    }
}
