server {
    listen 80;

    location /health {
        return 200 '{"status":"UP","server":"server3"}';
        add_header Content-Type application/json;
    }

    location / {
        return 200 '{"server":"server3","message":"Hello from Backend 3"}';
        add_header Content-Type application/json;
    }
}
