server:
  port: 8080

loadbalancer:
  health:
    check:
      interval: 10000
      timeout: 3000
  failure:
    threshold: 3
  proxy:
    timeout: 5000
  algorithm:
    default-algorithm: ROUND_ROBIN
  
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 60
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always